### ISSUE TITLE
Would it be possible to separate writing a varint vs. wring a zig-zag varint?

### ISSUE THREAD

**Issue by allengeorge** [dermesser/integer-encoding-rs#1]
Some background: I'm working on a thrift plugin that autogenerates Rust from a Thrift IDL. The compact wire-format uses both varints and zigzag encoded varints for numbers. From what I can tell they don't use zigzag encoding for some numbers (such as message sizes) because they're never negative.

I really wanted to use this crate but I noticed that the `impl VarInt` for `i64` and `u64` always zig-zag encodes the number before writing it out as a varint. Would there be a way to split this up? In other words, have a `write_varint` and `write_zigzag_varint`? I understand if you would prefer not to do this, but thought I'd ask.

Thank you - and I really appreciate your work on this crate - it's super clean!

**Comment by dermesser** [comment]
so it's been a while since I wrote that code, but IIRC it already does what you want.

So for all unsigned integers -- u16, u32, u64 -- the same implementation is used: https://github.com/dermesser/integer-encoding-rs/blob/master/src/varint.rs#L137 (smaller integers are first cast to u64). The implementation for unsigned integers should never use zigzag-encoding.

Only if you encode integers that are of a signed type should they be zigzag-encoded. It could be that I'm missing some important part, but at least that was my intention when implementing it :-)

**Comment by allengeorge** [comment]
Ah - you know what - you're absolutely right. I made a mistake by accidentally writing `i32` instead of `u32`. I'm so sorry about that, and thanks for pointing that out. Much appreciated!

**Comment by dermesser** [comment]
no worries :)
